# Generated by Django 3.1.7 on 2021-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210317_1857'),
        ('carts', '0006_auto_20210330_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='cart', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='savedforlater',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='saved_for_later', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='courses.Course'),
        ),
    ]
