# Generated by Django 3.1.7 on 2021-03-06 16:17

import courses.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('image', models.ImageField(upload_to=courses.utils.get_course_upload_image_path)),
                ('title', models.CharField(max_length=70)),
                ('subtitle', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=10)),
                ('description', models.TextField(max_length=1000)),
                ('students_count', models.IntegerField(default=0)),
                ('lections_count', models.IntegerField(default=0)),
                ('duration_time', models.TimeField(default=datetime.time(0, 0))),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
            ],
        ),
    ]
