# Generated by Django 3.1.7 on 2021-03-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210306_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lections_count',
            new_name='lectures_count',
        ),
    ]
