# Generated by Django 3.1.7 on 2021-03-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursegoal_courserequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_count', models.IntegerField(default=0)),
                ('lectures_count', models.IntegerField(default=0)),
                ('articles_count', models.IntegerField(default=0)),
                ('resources_count', models.IntegerField(default=0)),
                ('assignments_count', models.IntegerField(default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='courses.course')),
            ],
        ),
    ]
