# Generated by Django 3.1.7 on 2021-03-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedurationtime',
            name='course',
        ),
        migrations.AddField(
            model_name='coursedurationtime',
            name='course_content',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='duration_time', to='courses.coursecontent'),
        ),
    ]
