# Generated by Django 3.1.7 on 2021-03-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210309_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedurationtime',
            name='course_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration_time', to='courses.coursecontent'),
        ),
    ]
