# Generated by Django 3.1.7 on 2021-03-09 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210309_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=50)),
                ('lectures_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='lectures_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='articles_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='assignments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='lectures_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='resources_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='sections_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursedurationtime',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursedurationtime',
            name='minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.CreateModel(
            name='SectionDurationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('course_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration_time', to='courses.coursesection')),
            ],
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.coursecontent'),
        ),
    ]
