# Generated by Django 3.1.7 on 2021-03-09 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210309_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('free_opened', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('students_finished_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.coursesection')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseLectureDurationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('course_lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration_time', to='courses.courselecture')),
            ],
        ),
    ]
