# Generated by Django 3.1.7 on 2021-03-10 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210310_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselecturedurationtime',
            name='seconds',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
    ]
