# Generated by Django 3.1.7 on 2021-03-17 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_course_lectures_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='coursedurationtime',
            options={'verbose_name': 'Duration time', 'verbose_name_plural': 'Duration times'},
        ),
        migrations.AlterModelOptions(
            name='coursegoal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='courselecture',
            options={'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AlterModelOptions(
            name='courselecturedurationtime',
            options={'verbose_name': 'Lecture | Duration time', 'verbose_name_plural': 'Lectures | Duration times'},
        ),
        migrations.AlterModelOptions(
            name='courserequirement',
            options={'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='coursesectiondurationtime',
            options={'verbose_name': 'Section | Duration time', 'verbose_name_plural': 'Sections | Duration times'},
        ),
        migrations.AlterField(
            model_name='coursedurationtime',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='coursedurationtime',
            name='minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Minutes'),
        ),
    ]
