# Generated by Django 3.1.7 on 2021-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210317_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselecture',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
