# Generated by Django 3.1.7 on 2021-03-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20210317_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselecture',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='active',
        ),
    ]
