# Generated by Django 3.1.7 on 2021-03-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='active',
            new_name='published',
        ),
    ]
