# Generated by Django 3.2.3 on 2021-07-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='stripe_id',
            new_name='stripe_token',
        ),
    ]
