# Generated by Django 3.2.3 on 2021-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20210706_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='postal_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
