# Generated by Django 3.2.3 on 2021-07-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20210709_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='active',
        ),
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='card',
            name='default',
        ),
        migrations.RemoveField(
            model_name='card',
            name='stripe_id',
        ),
    ]
