# Generated by Django 3.2.3 on 2021-07-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='payment_method',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.paymentmethod'),
        ),
    ]
