# Generated by Django 3.2.3 on 2021-07-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_card_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.paymentmethod'),
        ),
    ]
