# Generated by Django 3.2.3 on 2021-07-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_card_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='active',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='default',
        ),
        migrations.AddField(
            model_name='card',
            name='billing_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.card'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(default='card', max_length=50),
            preserve_default=False,
        ),
    ]
