# Generated by Django 3.1.7 on 2021-04-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20210330_2106'),
        ('discounts', '0002_auto_20210404_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedcoupon',
            options={'verbose_name': 'Applied coupon', 'verbose_name_plural': 'Applied coupons'},
        ),
        migrations.RemoveField(
            model_name='appliedcoupon',
            name='applied_to',
        ),
        migrations.AlterField(
            model_name='appliedcoupon',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='carts.cart'),
        ),
    ]
