# Generated by Django 3.1.7 on 2021-04-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20210330_2106'),
        ('discounts', '0003_auto_20210404_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcoupon',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='carts.cart'),
        ),
    ]
