import enum


class DiscountErrorMessages(enum.Enum):
    INVALID_COUPON_INITIALIZATION_DATA_ERROR = "INVALID_COUPON_INITIALIZATION_DATA_ERROR"
    INVALID_APPLIED_COUPON_ERROR = "INVALID_APPLIED_COUPON_ERROR"
    REQUEST_FIELDS_ERROR = "REQUEST_FIELDS_ERROR"
 